[default]
engine = "kafka"

[kafka]
servers = "localhost:19092"

[kafka.producer]


[kafka.consumer]
group = "product-api"
start = "earliest"

[rabbitmq]
host = "localhost:5672"
queue = "rimdesk.product"
exchange = "rimdesk.product.exchange"